name: IrregularVerbs
options:
  bundleIdPrefix: com.boss
  deploymentTarget:
    iOS: "15.0"
targets:
  IrregularVerbs:
    type: application
    platform: iOS
    sources:
      - path: IrregularVerbs
    scheme: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.boss.irregularverbs
        PRODUCT_NAME: IrregularVerbs
        MARKETING_VERSION: "2.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Глаголы
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
